site_name: ShowControl Documentation
site_description: Operator Manual for ShowControl
site_author: KBLiveSolutions

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Installation / connection: connecting-the-device.md
  - Using setlists: using-setlists.md
  - Using user-defined controls: using-user-defined-controls.md
  - Quick Start (Performer): quickstart.md
  - Show Day Checklist: showday-checklist.md
  - Using Ableset: ableset.md
  - Troubleshooting: troubleshooting.md
  - Style Guide: STYLEGUIDE.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
